// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hardtowtofuuzejggihn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhhcmR0b3d0b2Z1dXplamdnaWhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMwMDczODUsImV4cCI6MjA1ODU4MzM4NX0._W1sDjoTAbvADFYFFInfgsH40kgIxw5pWObWxWqxOc8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);